config/routes.rb
Rails.application.routes.draw do
  get 'angular/index'

  devise_for :users
  resources :todos

  root 'todos#index'

end

app/models/todo.rb
class Todo
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :description, type: String
  field :completion, type: Integer

  validates :title, presence: true
  validates :completion, presence: true
  validates :completion, numericality: {greater_than: 0,less_than_or_equal_to: 100}

  after_initialize :add_created_at

  def add_created_at
    unless self.created_at.present?
      self.created_at = self.id.generation_time
      self.save
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  embeds_many :todos do
    def finished
      where(completion: 100)
    end
    # def unfinished
    #   where(completion: )
    # end
  end
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @todos = Todo.all
    respond_with(@todos)
  end

  def show
    respond_with(@todo)
  end

  def new
    @todo = Todo.new
    respond_with(@todo)
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    respond_with(@todo)
  end

  def update
    @todo.update(todo_params)
    respond_with(@todo)
  end

  def destroy
    @todo.destroy
    respond_with(@todo)
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:title, :description, :completion)
    end
end

app/helpers/angular_helper.rb
module AngularHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/angular/index.html.erb
<div ng-app="todoer">
  <div class="view-container">
    <div ng-view class="view-frame animate-view"></div>
  </div>
</div>

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  .top-bar-section
    %ul
      -#= render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html{'ng-app':'todoer'}
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Angular Mongo Todo List'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Angular Mongo Todo List'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .large-8.columns.large-centered
        = render 'layouts/messages'
        = yield

app/views/todos/_form.html.haml
= simple_form_for(@todo) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :completion

  .form-actions
    = f.button :submit

app/views/todos/edit.html.haml
%h1 Editing todo

= render 'form'

= link_to 'Show', @todo, class: 'button info'
\|
= link_to 'Back', todos_path, class: 'button'

app/views/todos/index.html.haml
%h1 Listing todos

%table#todos
  %thead
    %tr
      %th Title
      %th Description
      %th Completion
      %th

  %tbody
    - @todos.each do |todo|
      %tr
        %td= todo.title
        %td= todo.description
        %td.progress.success.small-2
          %span.meter{style:"width: #{todo.completion}%"}
        %td.action-buttons
          =link_to 'Show', todo, class: 'button tiny info'
          =link_to 'Edit', edit_todo_path(todo), class: 'button tiny'
          =link_to 'Destroy', todo, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'button tiny alert'

%br

= link_to 'New Todo', new_todo_path, class: 'button'

app/views/todos/new.html.haml
%h1 New todo

= render 'form'

= link_to 'Back', todos_path, class: 'button secondary'

app/views/todos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @todo.title
%p
  %b Description:
  = @todo.description
%p
  %b Completion:
  = @todo.completion

= link_to 'Edit', edit_todo_path(@todo), class: 'button info'
\|
= link_to 'Back', todos_path, class: 'button secondary'